# This workflow builds and tests the application. For testing it sets up Firebase emulators to run in the background.


name: Build and test


on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -f run_tests.Dockerfile . -t build_and_test
      - run: docker run build_and_test
